// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfkqwwmazqsceqefwxvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ma3F3d21henFzY2VxZWZ3eHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NjU0NzYsImV4cCI6MjA3NDM0MTQ3Nn0.pU9AuZzC8Athsx4RW73aG7KYutqVzlSLlKHgQ9MjTC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});