name: Windows via OpenVPN

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set permissions on first.ovpn
        shell: pwsh
        run: |
          $ovpn = Join-Path "${{ github.workspace }}" "first.ovpn"
          if (Test-Path $ovpn) {
            icacls $ovpn /inheritance:r /grant:r "$($env:USERNAME):(R)"
            Write-Host "Permissions updated for $ovpn"
          } else {
            Write-Host "first.ovpn not found in repository root."
          }

      - name: Enable Protocol (RDP)
        shell: pwsh
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user runneradmin MyP@ssw0rd123

      - name: RDP compat for TCP
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          New-Item -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -Force | Out-Null
          Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -Name 'SelectTransport' -Type DWord -Value 1
          Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name 'UserAuthentication' -Type DWord -Value 0
          Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name 'SecurityLayer' -Type DWord -Value 0
          Restart-Service TermService -Force

      - name: Install OpenVPN
        shell: pwsh
        run: |
          choco install -y openvpn

      - name: Start OpenVPN connection (foreground)
        shell: cmd
        run: |
          "C:\Program Files\OpenVPN\bin\openvpn.exe" --config "%GITHUB_WORKSPACE%\first.ovpn" --auth-nocache
